# Generated by Django 4.1.7 on 2023-07-06 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidorealizado',
            name='estado',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Empacado', 'Empacado'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Aceptado', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
